name: CD
on:
  release:
    types: [published]

jobs:
  add-binaries:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: "^1"

    - name: build
      run: ./build-prod

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./bin/genim-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
